services:
  frontend:
    build: ./frontend
    image: collabmate-frontend
    container_name: collabmate-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000

  backend:
    build: ./backend
    image: collabmate-backend
    container_name: collabmate-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./backend/data:/app/data
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
